### PR TITLE
Fix issue 9

### PR DESCRIPTION
**Pull request by ecascardo**

### CODE REVIEW

**Comment by eduardo-matos** [comment]
This issue only happens on Ubuntu image. It works just fine on any python image.

**Comment by eduardo-matos** [comment]
Sorry, I didn't realize this is a pull request.

I'll review it and publish by tomorrow.
Thanks for your contribution! @ecascardo

**Comment by petrklus** [comment]
Just checking in @eduardo-matos , is this making its way into a release?

**Comment by cyberbudy** [comment]
+1

**Pull request merged**
