### PR TITLE
Manager serialization for using them in migrations

### PR DESCRIPTION
**Pull request by PeRDy**
Use Django mechanism to allows custom managers in migrations.

### CODE REVIEW

**Comment by eduardo-matos** [comment]
@PeRDy
Do you have any idea on how I could test this?

**Comment by PeRDy** [comment]
I'd say that the faster method is to create a migration that uses the manager and try that it works. There you can find more info about it:

[https://docs.djangoproject.com/en/1.11/topics/migrations/#historical-models](https://docs.djangoproject.com/en/1.11/topics/migrations/#historical-models)
[https://docs.djangoproject.com/en/1.11/topics/migrations/](https://docs.djangoproject.com/en/1.11/topics/migrations/)

**Comment by eduardo-matos** [comment]
@PeRDy 
It looks like line 12 from `global_permissions/models.py` has a few whitespaces, which caused a lint error.
Can you please fix that?

**Comment by PeRDy** [comment]
@eduardo-matos done :)

**Pull request merged**
